### PR TITLE
Check installed.json

### PR DESCRIPTION
**Pull request by webflo**

### CODE REVIEW

**Comment by derhasi** [comment]
I do not get your changes. What do you want to achieve with it?

**Comment by webflo** [comment]
It is the result of a lengthy in IRC with @greg-1-anderson. I was trying to prevent the update of the scaffold in CI environments. I think we want to keep the committed scaffold file in any case, even if we install a new version of the package. Because a developer did the update before and committed the files already. ``composer install`` should not update the scaffold at all if the ``composer.lock`` is present.

**Comment by webflo** [comment]
The proposed solution is not correct, i still try to locate the proper information in the composer event.

**Comment by greg-1-anderson** [comment]
I think https://github.com/drupal-composer/drupal-scaffold/pull/7#issuecomment-162111702 is on the right track. `composer install` only installs the scaffold files if there are no scaffold files present.  `composer update` will update the scaffold files to the target version any time drupal/core is updated.

Since we are not trying to detect exact version changes in `composer install`, I think that the existing code, prior to this PR, is sufficient -- it already does the right thing for `composer update`.  I think all we need now is logic that says, "on `composer install`, only install if none of the files listed in "includes" exist on disk."

**Comment by greg-1-anderson** [comment]
I just added a commit to #6 to refactor this per my comment above. Next I'll add a check to see if any (all?) of the 'include' files already exist, and, if so, prevent install from updating the scaffold  files. Then I think we're pretty much there, save for the remaining limitation that we can't perfectly restore the scaffolding files to the same state after a `composer install` with a `composer.lock` in place when there are newer scaffold files in HEAD.

In IRC, @webflo and I seemed to think this limitation was acceptable for now, since it is advisable for folks to commit the scaffolding files to their repository anyway.

**Comment by greg-1-anderson** [comment]
I think #6 now satisfies our use-cases vis-a-vis `composer create-project` (scaffold files downloaded) and `composer install` from CI (scaffold files not downloaded if checked in).

**Comment by webflo** [comment]
@greg-1-anderson @derhasi Thought about it again, and we should check the composer.lock instead of installed.json. Checks against ``installed.json`` will fail on the initial clone/install of a repo with an existing lock file.

**Comment by webflo** [comment]
We should go with #8

**Comment by greg-1-anderson** [comment]
Closing in favor of #8 / #20; re-open if further discussion here is desired.

**Pull request closed without merging**
