### PR TITLE
Getting rid of wget dependency

### PR DESCRIPTION
**Pull request by derhasi**
The code has a dependency to the wget command line tool. As we can solve the task with curl too (and the extension is required by Drupal), we should replace that, I guess.

@greg-1-anderson, was there a reason you used wget over curl in the first place?

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
I was just thinking along these same lines this morning. I'm not sure why I used `exec wget` instead of a library. It was my thought that perhaps we should use guzzle here, as I presumed that we inherited that dependency from Robo anyway. However, it appears that is not the case.  Curl lib is always available, so I think the way you have it is best.

**Comment by webflo** [comment]
Guzzle is fine imo. Because its already a dependency of Drupal, means there is no overhead.

**Comment by derhasi** [comment]
Yep, guzzle is fine from my perspective, as it is required by drupal too.

**Comment by greg-1-anderson** [comment]
66f15cf inadvertently uses the Guzzle 3 APIs.  These are included indirectly via Drupal Console, which requries "alchemy/zippy": "0.2.*@dev", which brings in the old Guzzle.

Working on updated to use the newer API, but it also appears that we must include the autoloader ourselves when instantiating our own RoboRunner from a Composer Installer.  Not sure what the implications of that are; if it's not a good idea, we could always exec Robo instead.

**Comment by greg-1-anderson** [comment]
This does not work yet, as robo is, for some reason, unable to load our RoboFile in this circumstance. An empty RoboFile does load. That is as far as I traced it.

I think that ultimately we need to use a subprocess in order to cleanly and safely include our autoload file.

**Comment by derhasi** [comment]
Robo must not be called via exec, as it will not run in the autoloaded context. The RoboRunner is a custom runner that avoids being dependent of a robo file. I will have a look on this later today.

**Comment by derhasi** [comment]
The custom autoload you did in 635bfc39a475a5347dd1e380a2ff07bdb74bd070 is not necessary, as we are not using the CLI robo command. I reverted the last two commits and removed the autoloading. This seems to work.

**Comment by derhasi** [comment]
@greg-1-anderson, does this make sense for you? From my side the changes should be fine.

**Comment by greg-1-anderson** [comment]
Did you test this within the context of a drupal-project?  The code as you wrote it is what I originally had, and it worked for me in the drupal-scaffold unit tests, but not in a real project.  I'll try again -- maybe create a new project.

I'm not sure what you mean by `as it will not run in the autoloaded context`; also, it seems that we do have a RoboFile that our RoboRunner works with.  Perhaps this file is different than a standard RoboFile in some way I did not notice; that, at least, would explain my results with trying to use it with Robo.

**Comment by derhasi** [comment]
You are right. This seems to be related to https://www.drupal.org/node/2542564 and https://github.com/drush-ops/drush/issues/1519.

For the robo part: the custom `\DrupalComposer\DrupalScaffold\RoboRunner()` is tightly coupled to `\DrupalComposer\DrupalScaffold\RoboFile()`. That is necessary, so we can run robo in the same php process and so can have the advantages of autoloading.

I guess there is some missbehaviour in Guzzle itself, that disrupts the autoloading. I have to look further into it.

**Comment by greg-1-anderson** [comment]
I saw those issues that you mentioned, and I don't think that is the cause.  As I mentioned above, Drupal Console pulls in a component that brings in Guzzle 3, and it is working fine with Drupal core, which uses Guzzle 6.  I think that Guzzle fixed whatever problem was causing https://www.drupal.org/node/2542564. cc @jmolivas in case he has some insight here.

So, even though the reason is different, the cause is the same: for some unknown reason, the Guzzle 6 `files` from the autoloader are not being included, even though the classes are available.

Robo loads our autoloader as soon as it starts up, though, so I think we could fix this by de-coupling our RoboFile from our custom installer, and exec'ing Robo as I started to do above. This should work every bit as well as when we were doing this directly from [drupal-composer/drupal-project in an earlier commit](https://github.com/greg-1-anderson/drupal-project/blob/7be8c558879682b74947a28814b406a5d7c05463/scripts/drupal/RoboFile.php). We'd just need to fix that to take our `extra` parameters as options, as our current RoboFile does.

I'm also okay with moving forward with a fix to the autoloader problem, if you think you can track that down; however, that looks like it might be caused by a Composer bug, or maybe still a lingering Guzzle problem, although temporarily removing Drupal Console and Guzzle 3 did not improve the situation for me. Seems the exec route might be an easier fix, if it does work.

**Comment by greg-1-anderson** [comment]
I got Robo to work decoupled via exec.  The steps required were:

- Put RoboFile in the global namespace. If you're not using a RoboRunner, Robo doesn't seem to like it anywhere else. (Maybe there is a way....)
- Move RoboFile.php to a 'scripts' directory. Otherwise, you get a duplicate class error when Robo tries to load the RoboFile. (Omitting the --load-from does not help.)
- Stop using RoboFile::DELIMITER_EXCLUDE from Handler.php.  This actually seemed to be the only place where the RoboFile was tightly coupled with the Handler. It would probably work to move DELIMITER_EXCLUDE to Handler, and reference it from the RoboFile.
- Encapsulate the webroot in `realpath` before passing it to Robo. Robo sets the cwd to the scripts folder.
- Run Robo with `passthru` instead of `exec` so that the output is visible as it is produced.

I'll make a commit with these changes if you'd like, but I didn't want to do that in case you still wanted to investigate fixing the autoloader bug.  I think decoupling is the better solution here, but happy to go the other way if it's easy to fix and you like it better.

**Comment by greg-1-anderson** [comment]
I made a separate branch showing the decoupled 'exec' / 'passthru' solution. Seems to work well. Feel free to keep working on the autoloader fix here, or just merge #14 if you are fine with that solution.

**Comment by derhasi** [comment]
I will review this today ;)

**Comment by greg-1-anderson** [comment]
It would be great to come to resolution here, or #14; with the merge of #13, HEAD of master is broken, so I must continue to use a dev branch when working with this project.

**Comment by greg-1-anderson** [comment]
Would it be okay to merge #14, and maybe #17 and #18 as well?  I am feeling kind of blocked with HEAD broken, and the outstanding PRs overlapping. drupal-scaffold is not used in drupal-project yet, so we could always switch to other techniques later, once you have time to review.

**Comment by derhasi** [comment]
Yes, feel free to merge it. Did not have time to review as I thought. Might have a look at it within the next week, but I can open a fresh PR then, if I figured out what the problem was.

**Comment by greg-1-anderson** [comment]
Thanks. I merged #14; tomorrow I will fix the conflicts in #17 and #18 and merge those as well in the morning. This will allow us to update the PR in drupal-project to remove the scaffold files, although we will not be able to merge there until we come to a determination on #9, and revisit the issues here as necessary.

**Comment by greg-1-anderson** [comment]
Closing in favor of #14; re-open if continued discussion here is desired.

**Comment by derhasi** [comment]
This seems to be a problem with composer not loading the autoload files. I posted an issue to the composer issue queue: https://github.com/composer/composer/issues/4764

**Pull request closed without merging**
