### PR TITLE
Support NFS mounts between VMs and hosts by not changing file ownership information.

### PR DESCRIPTION
**Pull request by bartfeenstra**

### CODE REVIEW

**Comment by webflo** [comment]
I am in favour of this change because we use rsync as glorified copy command. I think it does not hurt if the files are written by the current user (same behaviour as copy without -p)

**Comment by webflo** [comment]
@greg-1-anderson Please review. Thanks!

**Comment by greg-1-anderson** [comment]
LGTM. I'll just merge this if @webflo has already confirmed @bartfeenstra 's results. Otherwise, I'll test and merge later.

**Comment by bartfeenstra** [comment]
FWIF, @webflo suggested this solution on IRC and wrote a PR for it. We've been using this in local/dev (VM with NFS sync) and CI (Travis, no NFS) environments since earlier today without any failures.

**Comment by bartfeenstra** [comment]
Thanks! When is the next version scheduled to be released?

**Comment by webflo** [comment]
Tagged 1.3.2 a few minutes ago

**Pull request merged**
