### PR TITLE
Fetch files via cgit.drupalcode.org directly

### PR DESCRIPTION
**Pull request by webflo**
Follow-up for #37

I tried to fix the async via guzzle in https://github.com/drupal-composer/drupal-scaffold/pull/38/commits/69038acdc673507632180a4389e8f8947ea9acf4#diff-972a789eb631b4e9b19070bc31cbe900L36 and was working in the test. It took lets than 4 seconds to fetch all files. But i hit https://github.com/composer/composer/issues/4764 if i run it as composer plugin :/

Refactored everything and used composers RemoteFileSystem to get the job done. Documentation is not up to date yet.

### CODE REVIEW

**Comment by webflo** [comment]
It should be faster (#35) and work on Windows (#11)

**Comment by greg-1-anderson** [comment]
Haven't tried it yet, but read through the changes and it looks fantastic. Great job.

**Comment by webflo** [comment]
@greg-1-anderson Why is expected that the index.php is not present after the initial composer install? Both packages (the scaffold and drupal core) is in the composer.json. I can't spot the difference to the previous implementation.

**Comment by greg-1-anderson** [comment]
I just ran `phpunit` locally, and the tests passed.  I'm going to have to scratch my head a bit about why the failure is happening on Travis; the cause is not immediately apparent to me.

**Comment by greg-1-anderson** [comment]
The only difference with the previous implementation was that the robo task was `exec`'ed, whereas now the files are fetched directly from the composer plugin process. However, I cannot reproduce this locally, so it's hard for me to imaging what it is about the Travis system that causes the test to fail there.

Does a local `phpunit` run pass for you?  I presume that it probably does.

**Comment by webflo** [comment]
https://github.com/drupal-composer/drupal-scaffold/pull/40 failed after composer update. I change the test to match the new behaviour. It makes more sense anyway. Thanks @greg-1-anderson for your help.

**Comment by greg-1-anderson** [comment]
LGTM.  Some minor changes to drupal-composer/drupal-project will be needed once this is merged.

**Comment by webflo** [comment]
@greg-1-anderson Yes the version constraint. What else?

**Comment by greg-1-anderson** [comment]
I added a PR, https://github.com/drupal-composer/drupal-project/issues/155 to demonstrate.  I think it's about right, but have not tried it.

**Pull request merged**
