### PR TITLE
Replace PrestissimoFileFetcher with Guzzle

### PR DESCRIPTION
**Pull request by webflo**
I was not able to resolve the error logging in https://github.com/drupal-composer/drupal-scaffold/issues/73. Therefore i tried to re-implement the feature on Guzzle again.

We had Guzzle some time about, but remove it because of dependency issues.

### CODE REVIEW

**Comment by webflo** [comment]
Its this error again

```
Generating autoload files

Fatal error: Uncaught Error: Call to undefined function GuzzleHttp\choose_handler() in /Users/fweber/Sites/app3/vendor/guzzlehttp/guzzle/src/HandlerStack.php:40
Stack trace:
#0 /Users/fweber/Sites/app3/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\HandlerStack::create()
#1 /Users/fweber/Sites/app3/vendor/drupal-composer/drupal-scaffold/src/GuzzleFileFetcher.php(36): GuzzleHttp\Client->__construct()
#2 /Users/fweber/Sites/app3/vendor/drupal-composer/drupal-scaffold/src/Handler.php(166): DrupalComposer\DrupalScaffold\GuzzleFileFetcher->fetch('8.5.4', '/Users/fweber/S...', true)
#3 /Users/fweber/Sites/app3/vendor/drupal-composer/drupal-scaffold/src/Handler.php(138): DrupalComposer\DrupalScaffold\Handler->downloadScaffold()
#4 /Users/fweber/Sites/app3/vendor/drupal-composer/drupal-scaffold/src/Plugin.php(83): DrupalComposer\DrupalScaffold\Handler->onPostCmdEvent(Object(Composer\Script\Event))
#5 [internal function]: DrupalComposer\DrupalScaffold\Plugin->postCmd(Object(Composer\Script\Event))
#6 phar:///opt/boxen/php in /Users/fweber/Sites/app3/vendor/guzzlehttp/guzzle/src/HandlerStack.php on line 40
````

Composer builds the autloader, but only PSR-0/4 autoloads, not file based.

**Comment by greg-1-anderson** [comment]
Yeah I have a solution for this - where did I put it? One moment.

**Comment by greg-1-anderson** [comment]
The issue is that Composer does not load the `files` section of Composer plugins' autoloader. I just need to remember which Composer plugin I was using Guzzle in. I think it was in some Composer scripts, which has the same issue.

**Comment by greg-1-anderson** [comment]
Not a great solution:

https://github.com/g1a/starter/blob/master/customize/Customizer.php#L22

**Comment by webflo** [comment]
Maybe we should defer the download operation until the autoloader has been build?

**Comment by greg-1-anderson** [comment]
It will work just fine if you include the Guzzle files that are needed; however, Guzzle could easily decide to chose to add more files to the include section or rename the files, etc., and these would not be breaking changes per SemVer.  It would be really grand if Guzzle would just move these functions into static class methods, as that would work from Composer plugins.

**Comment by greg-1-anderson** [comment]
I have not tried just manually including the autoload.php file. I'm not sure if this would or would not cause problems with Composer. The stated reason that Composer does not include the include files from the autoloader for plugins is that they cannot know if any given include file is idempotent. That is not a concern for Guzzle.

**Comment by webflo** [comment]
We should not pursue this longer. The fix in https://github.com/drupal-composer/drupal-scaffold/pull/88 is much smaller.

**Pull request closed without merging**
